/** @type {import('tailwindcss').Config} */
export default {
  // Classes live in both the static shell and in template literals inside the TypeScript
  // sources, so both have to be scanned. Every utility in this project is written as a
  // complete literal (verified - no `bg-${x}-500` style construction), which is what makes
  // a build-time scan equivalent to the runtime scanner the Play CDN used to run.
  content: ['./index.html', './src/**/*.{ts,js}'],

  theme: {
    extend: {
      // These three additions repair classes that were silently doing nothing. Tailwind v3
      // ships zIndex 0/10/20/30/40/50, blur without an `xs` step, and screens
      // sm/md/lg/xl/2xl - so `z-25`, `z-35`, `z-45`, `backdrop-blur-xs` and `xs:inline`
      // were never generated by the CDN build either. The markup has always asked for them,
      // so the stacking order of the scanline overlay / event feed / quest tracker /
      // calamity modal, the subtle modal blur, and the compact HUD labels never applied.

      /** Layering used by the HUD overlays in index.html. */
      zIndex: {
        25: '25',
        35: '35',
        45: '45'
      },

      /** `backdrop-blur-xs` is used as the subtlest step below `backdrop-blur-sm`. */
      backdropBlur: {
        xs: '2px'
      },

      /** `xs:` is used to reveal compact button labels on small phones but not on the
       *  narrowest ones, so it sits below Tailwind's default `sm` (640px). */
      screens: {
        xs: '480px'
      }
    }
  },

  plugins: []
};
